apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - name: jupyter
          image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/jupyter/base-notebook:latest
          ports:
            - containerPort: 8888
          args:
            - "start-notebook.sh"
            - "--NotebookApp.token=''"
            - "--NotebookApp.password=''"
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
spec:
  type: NodePort
  selector:
    app: jupyter
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30001